apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: {{ .Values.gcloud.name }}
  namespace: {{ .Values.gcloud.namespace }}
spec:
  template: {{ .Values.gcloud.template }} 
  credential: {{ .Values.gcloud.credential }} 
  config:
    project: {{ .Values.gcloud.project }}
    region: {{ .Values.gcloud.region }}
    network:
      name: {{ .Values.gcloud.networkName }}
    controlPlane:
      instanceType: {{ .Values.gcloud.cpInstanceType }}
      image: {{ .Values.gcloud.imageFamily }}
      publicIP: true
    controlPlaneNumber: {{ .Values.gcloud.cpReplicas }}
    worker:
      instanceType: {{ .Values.gcloud.workerInstanceType }}
      image: {{ .Values.gcloud.imageFamily }}
      publicIP: true
    workersNumber: {{ .Values.gcloud.workerReplicas }}
  serviceSpec:
    services:
      - name: ingress-nginx
        namespace: ingress-nginx
        template: ingress-nginx-4-13-0
      - name: argocd
        namespace: argocd
        template: argo-cd-7-8-0
        values: |
          redis-ha:
            enabled: true
          controller:
            replicas: 1
          server:
            autoscaling:
              enabled: true
              minReplicas: 2
          repoServer:
            autoscaling:
              enabled: true
              minReplicas: 2
          applicationSet:
            replicas: 2

